### ISSUE TITLE
Bugs in setup.sh

### ISSUE THREAD

**Issue by TeemuSuoranta** [samikeijonen/uuups#20]
Hi!

I'm giving Uuups a test run for one project outside work. I run into few issues with setup.sh:

- default_url is not replaced everywhere as it needs to be replaced in `webpack.settings.js`
- The name of the theme `default_name` cannot have spaces as it will break namespaces. This could have better instructions or separate namespace and the official name of the theme.
- As an enhancement you could also replace author name and url (see: https://github.com/aucor/aucor-starter/blob/master/setup.sh)

**Comment by samikeijonen** [comment]
Thanks @TeemuSuoranta! 

I should remove `setup.sh` since we don't use it anymore. We setup new theme using composer and rename via node. Here is [tutorial for installation](https://github.com/justintadlock/mythic/wiki/Installation).

I should write my own docs since Uuups is getting a little different than Mythic.

**Comment by samikeijonen** [comment]
Closed via 5a5e887e714e2270687441d349d200daef56dc06.
